id: hl7.fhir.us.mcode
canonical: http://hl7.org/fhir/us/mcode
version: 1.5.0
name: MinimalCommonOncologyDataElements
title: "minimal Common Oncology Data Elements (mCODE) Implementation Guide"
status: draft
publisher:
  name: HL7 International Clinical Interoperability Council
  url: http://www.hl7.org/Special/committees/cic
  email: ciclist@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: mCODEâ„¢ (short for Minimal Common Oncology Data Elements) is an initiative
  intended to assemble a core set of structured data elements for oncology
  electronic health records.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.0
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
copyrightYear: 2019+
releaseLabel: pre-STU2 draft
pages:
  index.md:
    title: Home
  conformance.md:
    title: Conformance
  group-patient.md:
    title: Patient Information
  group-disease.md:
    title: Disease Characterization
  group-genomics.md:
    title: Genomics
  group-labvital.md:
    title: Laboratory Results and Vital Signs
  group-treatment.md:
    title: Treatments
  group-outcome.md:
    title: Outcomes 
  examples.md:
    title: Extended Example
  downloads.md:
    title: Downloads
  change_log.md:
    title: Change log
menu:
  Home: index.html
  Content by Group:
    Patient: group-patient.html
    Disease: group-disease.html
    Laboratory: group-labvital.html
    Genomics: group-genomics.html
    Treatment: group-treatment.html
    Outcome: group-outcome.html
  All Artifacts: artifacts.html
  Extended Example: examples.html
  Conformance: conformance.html
  Downloads: downloads.html
  Change Log: change_log.html
  History: http://hl7.org/fhir/us/mcode/history.html

