id: hl7.fhir.us.mcode
canonical: http://hl7.org/fhir/us/mcode
version: 1.17.1
name: MinimalCommonOncologyDataElements
title: "minimal Common Oncology Data Elements (mCODE) Implementation Guide"
status: draft
publisher:
  name: HL7 International Clinical Interoperability Council
  url: http://www.hl7.org/Special/committees/cic
  email: ciclist@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: mCODEâ„¢ (short for Minimal Common Oncology Data Elements) is an initiative
  intended to assemble a core set of structured data elements for oncology
  electronic health records.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.0
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
copyrightYear: 2019+
releaseLabel: STU 2 (Post-Ballot, Pre-Publication Draft)
pages:
  index.md:
    title: Home
  group-patient.md:
    title: Patient Information
  group-disease.md:
    title: Disease Characterization
  group-assessment.md:
    title: Assessment
  group-genomics.md:
    title: Genomics
  group-treatment.md:
    title: Treatments
  group-outcome.md:
    title: Outcomes
  conformance-general.md:
    title: Conformance Expectations
  conformance-patients.md:
    title: Identifying In-Scope Patients
  conformance-profiles.md:
    title: Profile Conformance
  terminology.md:
    title: Terminology
  examples.md:
    title: Extended Example
  artifacts.html:
    title: Artifacts Summary
  dictionary.md:
    title: Data Dictionary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
menu:
  Home: index.html
  Content by Group:
    Patient: group-patient.html
    Disease: group-disease.html
    Assessment: group-assessment.html
    Genomics: group-genomics.html
    Treatment: group-treatment.html
    Outcome: group-outcome.html
  Conformance:
    General Expectations: conformance-general.html
    Identifying mCODE Patients: conformance-patients.html
    Profile Conformance: conformance-profiles.html
    Terminology: terminology.html
  Extended Example: examples.html
  Artifacts:
    All FHIR Artifacts: artifacts.html
    Data Dictionary: dictionary.html
    Other Downloads: downloads.html
  History:
    Change Log: change_log.html
    Other Versions: http://hl7.org/fhir/us/mcode/history.html
